@startuml

' Only greyscale
skinparam monochrome true
' Disable shadows
skinparam shadowing false

start

:Action 1;
:Action 2;

while(Parse result) is (success)

  if (case 1) then (yes)
    :Action 1;
  elseif (case 2)
    :Action 1;
    :Action 2;
  elseif (case 3)  
    :Action 1;
    stop
  endif

endwhile(failure)

stop

@enduml
